services:
  - type: web
    name: mp-notifier-v2
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn server_v2:app
    autoDeploy: true
    runtime: python-3.11.6
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: FERNET_KEY
        sync: false
      - key: POLLING_INTERVAL_SECONDS
        value: 30
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
